version: '3.2'
services:
  ipmi-exporter:
    image: prometheuscommunity/ipmi-exporter:v1.8.0
    container_name: hpc-monitor-ipmi-exporter
    ports:
      - "9290:9290"
    command:
      - --config.file=/ipmi-exporter.yml
    volumes:
      - ./ipmi-exporter.yml:/ipmi-exporter.yml
  node-exporter:
    image: prom/node-exporter:v1.6.1
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"  # Expose Node Exporter's metrics port
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - ./collectors/metrics:/metrics:ro  # Ensure the metrics dir is correct
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($|/)"
      - --collector.textfile.directory=/metrics  # Adjusted path to match the mount point

  prometheus:
    image: prom/prometheus:v2.50.1
    container_name: hpc-monitor-prometheus
    environment:
      TZ: Asia/Shanghai
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/targets.yml:/etc/prometheus/targets.yml
      - ./prometheus/rule.yml:/etc/prometheus/rule.yml
      - ./prometheus/data:/prometheus  # persist data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle' # https://prometheus.io/docs/prometheus/latest/configuration/configuration/#configuration
    depends_on:
      - ipmi-exporter

  mysql:
    image: mysql:8.0.36
    container_name: hpc-monitor-mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: Root@2024
      MYSQL_DATABASE: monitor
      MYSQL_USER: admin
      MYSQL_PASSWORD: Root@2024
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/tables.sql:/docker-entrypoint-initdb.d/tables.sql


  web:
    image: openjdk:21
    container_name: hpc-monitor-web
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8080:8080"
    volumes:
      - ./hpc-monitor-web-0.1.0.jar:/web-api.jar
      - ./prometheus:/prometheus
    entrypoint: [ "java","-jar","/web-api.jar","--spring.profiles.active=prod" ]
    depends_on:
      - prometheus
      - mysql

  nginx:
    image: nginx:1.25.5
    container_name: hpc-monitor-nginx
    environment:
      TZ: Asia/Shanghai
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/html:/etc/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true #容器内的root有真正的root权限，否则只是一个普通用户，没有.conf文件权限
    depends_on:
      - web



